window.translations = {
  kk: {
    title: "Healthkeys - сіздің денсаулығыныздың кілті",
    "menu.home": "Басты бет",
    "menu.profile": "Профиль",
    "menu.about": "Біз туралы",
    "menu.services": "Қызметтер",
    "menu.fitness": "Фитнес және денсаулық",
    "menu.contacts": "Байланыс",

    "main.title": "Сізге арналған виртуалды медициналық қызмет",
    "main.subtitle": "Денсаулық пен фитнеске арналған кеңестер – белсенді өмірдің кілті",
    "main.button": "Кеңес алу",

    "about.tag": "Біз туралы",
    "about.welcome": "Қош келдіңіз <span>HealthKeys</span>",
    "about.text": "Сіздің денсаулығыңыз – біздің басты басымдығымыз.",
    "about.more1": "Біз ең жақсы медициналық қызмет деңгейін қамтамасыз етуге тырысамыз.",
    "about.more2": "Дәрігерлер тобы озық диагностика мен емдеу әдістерін қолданады.",
    "about.readmore": "Толығырақ оқу →",

    "feature1.title": "Кәсіпқойлар",
    "feature1.desc": "Халықаралық тәжірибесі бар дәрігерлер.",
    "feature1.more": "Мамандарымыз әлемнің жетекші клиникаларында білім алып, тәжірибе жинақтады.",
    "feature2.title": "Технологиялар",
    "feature2.desc": "Заманауи жабдықтар мен әдістер.",
    "feature2.more": "Біз заманауи технологияларды — сандық диагностика мен роботтандырылған емдеуді қолданамыз.",
    "feature3.title": "Қамқорлық",
    "feature3.desc": "Жеке көзқарас.",
    "feature3.more": "Әр пациентке жеке көзқарас танытамыз, оның қажеттіліктерін ескереміз.",

    "services.title": "Біздің қызметтер",
    "services.description": "Біз сізге ең жақсы таңдауды ұсынамыз. Жоғары білікті мамандармен бірге дұрыс қызмет түрін таңдаңыз.",

    "services.doctor.title": "Дәрігер таңдау",
    "services.doctor.text": "Дұрыс маманды таңдау – тиімді емнің негізі. Тек білікті дәрігер ғана дұрыс диагноз қойып, оңтайлы ем жоспар ұсына алады.",
    "services.supplements.title": "БАД таңдау",
    "services.supplements.text": "Жеке дәрумендер мен нутриенттер кешені. Сәйкес БАД-тар күш-қуатты қалпына келтіреді, иммунитетті нығайтады.",
    "services.consult.title": "Кеңес беру",
    "services.consult.text": "Біз сіздің денсаулығыңызға сай ең тиімді шешімді таңдауға көмектесеміз.",
    "services.fitness.title": "Фитнес бағдарламалары",
    "services.fitness.text": "Мақсаттарыңызға сай тиімді жаттығулар. Денсаулықты жақсартып, төзімділікті арттырады.",
    "services.urgent.title": "Жедел жәрдем",
    "services.urgent.text": "Тәулік бойы жедел көмек. Өзімізге, отбасымызға қауіпсіздік пен сенімділік.",
    "services.monitoring.title": "Денсаулықты бақылау",
    "services.monitoring.text": "Медициналық тарих пен мәліметтерді сақтау — сапалы күтім мен нақты диагноз кепілі.",

    "footer.desc": "HealthKeys барлық адамдар үшін қолжетімді прогрессивті медициналық қызмет көрсетеді.",
    "footer.region": "Аймақ",
    "footer.address": "Мекенжай",
    "footer.help": "Көмек",
    "fitness.block1.title": "Денсаулық пен фитнеске арналған кеңестер: белсенді өмірдің кілті",
    "fitness.block1.text": "Денсаулық пен физикалық пішінге көңіл бөлу – ұзақ әрі қуатты өмірдің кепілі. Жаттығулар бұлшықеттерді нығайтып, төзімділікті арттырады және дене салмағын сақтауға көмектеседі. Толыққанды тамақтану ағзаны қажетті заттармен қамтамасыз етіп, жақсы көңіл-күй береді. Күні бойы жеткілікті мөлшерде таза су ішіп, су балансын сақтаңыз. Сапалы ұйқы қалпына келуге және күйзелісті азайтуға көмектеседі. Жаттығу алдында міндетті түрде қыздыру жасаңыз.",

    "fitness.block2.title": "Денсаулық пен фитнеске арналған пайдалы кеңестер",
    "fitness.block2.text": "Салауатты өмір салты – ұзақ өмір мен жақсы денсаулықтың негізі. Тұрақты физикалық белсенділік бұлшықетті күшейтіп, төзімділікті жақсартады. Теңгерімді тамақтану ағзаны қуаттандырады. Су ішуді ұмытпаңыз – бұл дене сұйықтығын сақтайды. Жақсы ұйқы – қалпына келу мен күйзелісті азайтудың негізі. Жаттығу алдында қыздыру жасаңыз – бұл жарақаттанудан сақтайды. Оң қалыпта жүріңіз – омыртқаңызды қорғаңыз. Терең дем алыңыз – бұл жүрек пен мидың жұмысын жақсартады. Денеңізді тыңдаңыз – артық жүктемеден сақ болыңыз.",

    "login": "Кіру",
    "email_or_phone": "Email немесе телефон",
    "password": "Құпия сөз",
    "forgot_password": "Құпия сөзді ұмыттыңыз ба?",
    "no_account": "Аккаунтыңыз жоқ па?",
    "register": "Тіркелу",
    "about.readmore": "Толығырақ оқу →",
    "home": "Басты бет",
    "about_us": "Біз туралы",
    "services": "Қызметтер",
    "fitness": "Фитнес және денсаулық",
    "register": "Тіркелу",
    "home": "Басты бет",
    "about_us": "Біз туралы",
    "services": "Қызметтер",
    "fitness": "Фитнес және денсаулық",
    "full_name": "Толық аты",
    "username": "Пайдаланушы аты",
    "phone": "Телефон нөмірі",
    "email": "Электрондық пошта",
    "password": "Құпия сөз",
    "confirm_password": "Құпия сөзді растаңыз",
    "gender": "Жынысы",
    "male": "Ер",
    "female": "Әйел",
    "not_specified": "Көрсетілмеген",
    "profile": "Профиль",
    "home": "Басты бет",
    "about_us": "Біз туралы",
    "services": "Қызметтер",
    "fitness": "Фитнес және денсаулық",
    "contacts": "Байланыс",
    "edit": "Өзгерту",
    "logout": "Шығу",
    "full_name": "Толық аты",
    "username": "Пайдаланушы аты",
    "gender": "Жынысы",
    "country": "Ел",
    "language": "Тіл",
    "timezone": "Уақыт белдеуі",
    "my_email": "Менің Email-ім",
    "forgot_password": "Құпиясөзді ұмыттыңыз ба?",
    "email_label": "Электрондық пошта",
    "send_reset_link": "Қалпына келтіру сілтемесін жіберу",
    "reset_password": "Құпиясөзді қалпына келтіру",
    "new_password": "Жаңа құпиясөз",
    "confirm_password": "Құпиясөзді растау",
    "reset_password_button": "Қалпына келтіру",
    "main.button": "Толығырақ ",
"fitblock.page_title": "Фитнес бағдарламасы",
  "fitblock.title": "Фитнес бағдарламасы",
  "fitblock.subtitle": "Денеңізді шынықтыру үшін күн сайынғы қарапайым жаттығулар",
  "fitblock.day1.title": "1-күн",
  "fitblock.day1.text": "Жеңіл жүгіру, приседания, планка",
  "fitblock.day2.title": "2-күн",
  "fitblock.day2.text": "Кардио, велосипед, қол жаттығулары",
  "fitblock.day3.title": "3-күн",
  "fitblock.day3.text": "Йога, тыныс алу, серуен",
  "fitblock.day4.title": "4-күн",
  "fitblock.day4.text": "Арқа, иық, итеру жаттығулары",
  "fitblock.day5.title": "5-күн",
  "fitblock.day5.text": "Секіргіш, пресс, созылу",
  "fitblock.day6.title": "6-күн",
  "fitblock.day6.text": "Жаяу жүру, су, тынығу",
  "fitblock.day7.title": "7-күн",
  "fitblock.day7.text": "Қайталау немесе толық демалыс",
  "diet.full_text": "Жемістер, көкөністер, бұршақ тұқымдастар (мысалы, жасымық, үрмебұршақ), жаңғақтар мен дәнді дақылдар (мысалы, өңделмеген жүгері, тары, сұлы, бидай және тазартылмаған күріш). Күніне кемінде 400 г (яғни бес порция) жемістер мен көкөністер тұтыну қажет, картоп, тәтті картоп, маниок және крахмалды тамыр дақылдарын есептемегенде. Бос қанттар жалпы энергия тұтынудың 10%-нан аз болу керек (шамамен 50 г немесе 12 шай қасық), бірақ денсаулықты жақсарту үшін 5%-дан аз болу ұсынылады. Бос қанттар — тағамдарға немесе сусындарға қосылатын қанттар және табиғи түрде балда, шәрбаттарда, шырындарда кездесетін қанттар. Майлар жалпы энергияның 30%-ынан аспауы керек. Артық салмақтың алдын алу үшін қанықпаған майларға (балық, авокадо, жаңғақтар, күнбағыс, соя, рапс, зәйтүн майлары) басымдық беру қажет. Қаныққан майлар (ет, сары май, пальма, кокос майлары) мен трансмайлардан (фабрикалық өнімдерде, фастфудта) бас тарту ұсынылады. Трансмайлар 1%-дан аспауы керек. Күніне 5 г-нан аз тұз тұтыну керек және ол йодталған болуы тиіс.\n\nАлғашқы екі жылдағы дұрыс тамақтану – баланың өсуі мен дамуына негіз болады, әрі артық салмақ пен аурулардың алдын алады. Алғашқы 6 айда тек ана сүтімен емізу қажет. 6 айдан кейін қосымша тағамдар енгізіліп, емізу 2 жасқа дейін жалғасуы тиіс. Қосымша тағамдар пайдалы әрі қауіпсіз болуы керек, тұз бен қант қоспаңыз.",
    "diet.title":"Дұрыс тамақтану келесі компоненттерді қамтиды:"
  },

  ru: {
    title: "Healthkeys - ключ к вашему здоровью",
    "menu.home": "Главная",
    "menu.profile": "Профиль",
    "menu.about": "О нас",
    "menu.services": "Наши сервисы",
    "menu.fitness": "Фитнес и здоровье",
    "menu.contacts": "Контакты",

    "main.title": "Виртуальное медицинское обслуживание для вас",
    "main.subtitle": "Советы для здоровья и фитнеса: ключ к активной жизни",
    "main.button": "Проконсультироваться",

    "about.tag": "О платформе",
    "about.welcome": "Добро пожаловать в <span>HealthKeys</span>",
    "about.text": "Ваше здоровье – наш главный приоритет.",
    "about.more1": "Мы делаем всё, чтобы обеспечить лучший уровень медицинского обслуживания.",
    "about.more2": "Команда врачей использует передовые методы диагностики и лечения.",
    "about.readmore": "Читать далее →",

    "feature1.title": "Профессионалы",
    "feature1.desc": "Опытные врачи с международной практикой.",
    "feature1.more": "Наши специалисты обучались в лучших клиниках мира и решают сложные медицинские случаи.",
    "feature2.title": "Технологии",
    "feature2.desc": "Современное оборудование и подходы.",
    "feature2.more": "Применяем цифровую диагностику и роботизированную хирургию.",
    "feature3.title": "Забота",
    "feature3.desc": "Индивидуальный подход к каждому.",
    "feature3.more": "Мы слушаем, поддерживаем и учитываем особенности каждого пациента.",

    "services.title": "Наши сервисы",
    "services.description": "Мы предлагаем вам лучший выбор. Найдите подходящую услугу для вашего здоровья с нашей помощью.",

    "services.doctor.title": "Подобрать врача",
    "services.doctor.text": "Выбор правильного специалиста — ключ к эффективному лечению. Только квалифицированный врач может подобрать оптимальный план.",
    "services.supplements.title": "Подбор БАД",
    "services.supplements.text": "Индивидуальный комплекс витаминов и нутриентов. Помогает восстановиться и укрепить иммунитет.",
    "services.consult.title": "Консультация",
    "services.consult.text": "Качественная консультация на основе опыта и индивидуального подхода.",
    "services.fitness.title": "Фитнес-программы",
    "services.fitness.text": "Программы, подобранные под здоровье и цели, улучшают выносливость и предотвращают стресс.",
    "services.urgent.title": "Неотложная помощь",
    "services.urgent.text": "Круглосуточная помощь для всей семьи — комфортно и безопасно.",
    "services.monitoring.title": "Мониторинг здоровья",
    "services.monitoring.text": "Храните историю и данные здоровья для точных диагнозов и рекомендаций.",

    "footer.desc": "HealthKeys обеспечивает прогрессивное медицинское обслуживание...",
    "footer.region": "Регион",
    "footer.address": "Адрес",
    "footer.help": "Помощь",
    "fitness.block1.title": "Советы для здоровья и фитнеса: ключ к активной жизни",
    "fitness.block1.text": "Забота о здоровье и физической форме — залог долгой и энергичной жизни. Регулярные тренировки укрепляют мышцы, улучшают выносливость и помогают поддерживать оптимальный вес. Полноценное питание обеспечивает организм всеми необходимыми веществами. Пейте достаточно воды в течение дня. Качественный сон восстанавливает организм и снижает стресс. Разминка перед тренировкой — обязательна.",

    "fitness.block2.title": "Полезные советы для здоровья и фитнеса",
    "fitness.block2.text": "ЗОЖ — это основа долголетия и отличного самочувствия. Тренировки укрепляют тело и повышают выносливость. Сбалансированное питание даёт энергию. Поддерживайте водный баланс, пейте чистую воду. Сон — ключ к восстановлению. Разминка перед нагрузкой помогает избежать травм. Следите за осанкой. Дышите глубже — это полезно для сердца и мозга. Слушайте своё тело — не переутомляйтесь.",
    "login": "Вход",
    "email_or_phone": "Email или телефон",
    "password": "Пароль",
    "forgot_password": "Забыли пароль?",
    "no_account": "Нет аккаунта?",
    "register": "Регистрация",
    "home": "Главная",
    "about_us": "О нас",
    "services": "Наши сервисы",
    "fitness": "Фитнес и здоровье",
    "register": "Регистрация",
    "home": "Главная",
    "about_us": "О нас",
    "services": "Наши сервисы",
    "fitness": "Фитнес и здоровье",
    "full_name": "Полное Имя",
    "username": "Имя пользователя",
    "phone": "Номер телефона",
    "email": "Почта",
    "password": "Пароль",
    "confirm_password": "Подтвердить пароль",
    "gender": "Пол",
    "male": "Мужской",
    "female": "Женский",
    "not_specified": "Не указывать",
    "profile": "Профиль",
    "home": "Главная",
    "about_us": "О нас",
    "services": "Наши сервисы",
    "fitness": "Фитнес и здоровье",
    "contacts": "Контакты",
    "edit": "Редактировать",
    "logout": "Выйти",
    "full_name": "Полное имя",
    "username": "Имя пользователя",
    "gender": "Пол",
    "country": "Страна",
    "language": "Язык",
    "timezone": "Часовой пояс",
    "my_email": "Мой Email",
    "forgot_password": "Забыли пароль?",
    "email_label": "Электронная почта",
    "send_reset_link": "Отправить ссылку сброса",
    "reset_password": "Сброс пароля",
    "new_password": "Новый пароль",
    "confirm_password": "Подтвердить пароль",
    "reset_password_button": "Сбросить",
"fitblock.page_title": "Фитнес программа",
  "fitblock.title": "Фитнес программа",
  "fitblock.subtitle": "Простые ежедневные упражнения для укрепления тела",
  "fitblock.day1.title": "День 1",
  "fitblock.day1.text": "Лёгкий бег, приседания, планка",
  "fitblock.day2.title": "День 2",
  "fitblock.day2.text": "Кардио, велосипед, упражнения на руки",
  "fitblock.day3.title": "День 3",
  "fitblock.day3.text": "Йога, дыхательные упражнения, прогулка",
  "fitblock.day4.title": "День 4",
  "fitblock.day4.text": "Упражнения на спину, плечи, отжимания",
  "fitblock.day5.title": "День 5",
  "fitblock.day5.text": "Скакалка, пресс, растяжка",
  "fitblock.day6.title": "День 6",
  "fitblock.day6.text": "Ходьба, вода, восстановление",
  "fitblock.day7.title": "День 7",
  "fitblock.day7.text": "Повторение или полный отдых"

  },

  en: {
    title: "Healthkeys - your key to health",
    "menu.home": "Home",
    "menu.profile": "Profile",
    "menu.about": "About us",
    "menu.services": "Services",
    "menu.fitness": "Fitness & Health",
    "menu.contacts": "Contacts",

    "main.title": "Virtual medical care for you",
    "main.subtitle": "Health and fitness tips: the key to an active life",
    "main.button": "Get a consultation",

    "about.tag": "About us",
    "about.welcome": "Welcome to <span>HealthKeys</span>",
    "about.text": "Your health is our top priority.",
    "about.more1": "We strive to provide the best level of medical service.",
    "about.more2": "Our doctors use advanced diagnostics and treatment methods.",
    "about.readmore": "Read more →",

    "feature1.title": "Professionals",
    "feature1.desc": "Experienced doctors with international practice.",
    "feature1.more": "They are trained in top global clinics and can handle complex medical situations.",
    "feature2.title": "Technologies",
    "feature2.desc": "Modern equipment and methods.",
    "feature2.more": "We apply the latest digital diagnostics and robotic surgery.",
    "feature3.title": "Care",
    "feature3.desc": "Individual approach for everyone.",
    "feature3.more": "We focus on trust and tailor care to each person’s needs.",

    "services.title": "Our Services",
    "services.description": "We offer you the best choice tailored to your needs. Get help from skilled professionals.",

    "services.doctor.title": "Find a Doctor",
    "services.doctor.text": "The right specialist is key to effective treatment. A qualified doctor offers the best recovery path.",
    "services.supplements.title": "Supplements Selection",
    "services.supplements.text": "Personalized vitamins and nutrients. Balanced supplements restore strength and improve well-being.",
    "services.consult.title": "Consultation",
    "services.consult.text": "We help you find the best solution based on experience and your health condition.",
    "services.fitness.title": "Fitness Programs",
    "services.fitness.text": "Workouts aligned with your goals and health — safe and efficient.",
    "services.urgent.title": "Emergency Help",
    "services.urgent.text": "24/7 support for you and your family — feel safe and confident.",
    "services.monitoring.title": "Health Monitoring",
    "services.monitoring.text": "Track your full medical history for accurate diagnosis and personalized care.",

    "footer.desc": "HealthKeys provides progressive medical care accessible to everyone.",
    "footer.region": "Region",
    "footer.address": "Address",
    "footer.help": "Help",
    "fitness.block1.title": "Health and fitness tips: the key to an active life",
    "fitness.block1.text": "Taking care of your health and fitness is the key to a long and energetic life. Regular exercise strengthens muscles, improves endurance, and helps maintain a healthy weight. Proper nutrition fuels the body with essential nutrients. Drink enough clean water daily. Quality sleep helps you recover and reduce stress. Don’t forget to warm up before workouts.",

    "fitness.block2.title": "Useful tips for health and fitness",
    "fitness.block2.text": "A healthy lifestyle is the foundation of longevity and well-being. Regular workouts strengthen your body and improve endurance. Balanced nutrition keeps your body energized. Stay hydrated. Get enough sleep to recover and reduce stress. Always warm up before exercise to prevent injury. Maintain good posture. Deep breathing improves heart and brain function. Listen to your body and avoid overtraining.",
    "login": "Login",
    "email_or_phone": "Email or phone",
    "password": "Password",
    "forgot_password": "Forgot password?",
    "no_account": "Don't have an account?",
    "register": "Sign up",
    "home": "Home",
     "about.readmore": "read more",
    "about_us": "About us",
    "services": "Services",
    "fitness": "Fitness & Health",
    "register": "Register",
    "home": "Home",
    "about_us": "About us",
    "services": "Services",
    "fitness": "Fitness & Health",
    "full_name": "Full Name",
    "username": "Username",
    "phone": "Phone Number",
    "email": "Email",
    "password": "Password",
    "confirm_password": "Confirm Password",
    "gender": "Gender",
    "male": "Male",
    "female": "Female",
    "not_specified": "Prefer not to say",
     "profile": "Profile",
    "home": "Home",
    "about_us": "About us",
    "services": "Services",
    "fitness": "Fitness & Health",
    "contacts": "Contacts",
    "edit": "Edit",
    "logout": "Logout",
    "full_name": "Full Name",
    "username": "Username",
    "gender": "Gender",
    "country": "Country",
    "language": "Language",
    "timezone": "Timezone",
    "my_email": "My Email",
    "forgot_password": "Forgot Password?",
    "email_label": "Email",
    "send_reset_link": "Send Reset Link",
    "reset_password": "Reset Password",
    "new_password": "New Password",
    "confirm_password": "Confirm Password",
    "reset_password_button": "Reset Password",
     "diet_title": "Healthy Diet Plan",
"fitblock.page_title": "Fitness Program",
  "fitblock.title": "Fitness Program",
  "fitblock.subtitle": "Simple daily exercises to strengthen your body",
  "fitblock.day1.title": "Day 1",
  "fitblock.day1.text": "Light jogging, squats, plank",
  "fitblock.day2.title": "Day 2",
  "fitblock.day2.text": "Cardio, cycling, arm exercises",
  "fitblock.day3.title": "Day 3",
  "fitblock.day3.text": "Yoga, breathing, walking",
  "fitblock.day4.title": "Day 4",
  "fitblock.day4.text": "Back, shoulder, push-up exercises",
  "fitblock.day5.title": "Day 5",
  "fitblock.day5.text": "Jump rope, abs, stretching",
  "fitblock.day6.title": "Day 6",
  "fitblock.day6.text": "Walking, hydration, recovery",
  "fitblock.day7.title": "Day 7",
  "fitblock.day7.text": "Repeat or full rest",
    "diet.full_text": "Fruits, vegetables, legumes (such as lentils and beans), nuts and whole grains (like unprocessed corn, millet, oats, wheat, and brown rice). At least 400 g (five portions) of fruits and vegetables daily, excluding potatoes, sweet potatoes, cassava and other starchy roots. Free sugars should be less than 10% of total energy intake (about 50 g or 12 teaspoons), ideally less than 5%. Free sugars include those added to foods and drinks, as well as those naturally present in honey, syrups, and fruit juices. Fats should be less than 30% of total energy intake. Prefer unsaturated fats (in fish, avocado, nuts, sunflower, soybean, canola, and olive oils), and avoid saturated fats (fatty meat, butter, palm/coconut oils) and trans fats. Trans fats should be less than 1%. Salt intake should be under 5 g per day and iodized.\n\nOptimal nutrition in the first two years of life promotes healthy growth and reduces the risk of overweight",
    "diet.title":"A healthy diet includes the following components:"


  }
};

function setLang(lang) {
  localStorage.setItem("lang", lang);
  const elements = document.querySelectorAll("[data-i18n]");
  elements.forEach(el => {
    const key = el.getAttribute("data-i18n");
    const value = window.translations[lang] && window.translations[lang][key];
    if (value) {
      if (key === "title") {
        document.title = value;
      } else {
        el.innerHTML = value;
      }
    }
  });
}

document.addEventListener("DOMContentLoaded", () => {
  const savedLang = localStorage.getItem("lang") || "kk";
  setLang(savedLang);
  const selector = document.querySelector(".change-lang");
  if (selector) {
    selector.value = savedLang;
    selector.addEventListener("change", e => setLang(e.target.value));
  }
});
